export interface StateConfig {
  name: string;
  abbreviation: string;
  slug: string;
  availableGames: string[];
  taxRate: number;
  taxNotes?: string;
  lotteryWebsite: string;
  claimInfo: string;
  purchaseAge: number;
  facts: string[];
}

export const stateConfigs: Record<string, StateConfig> = {
  california: {
    name: 'California',
    abbreviation: 'CA',
    slug: 'california',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0,
    taxNotes: 'California does not tax lottery winnings — one of the best states to win!',
    lotteryWebsite: 'https://www.calottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any retailer. Prizes $600-$5,000 at CA Lottery District Offices. Over $5,000 at CA Lottery headquarters in Sacramento.',
    purchaseAge: 18,
    facts: [
      'California Lottery was established in 1984',
      'No state tax on lottery winnings',
      'One of the largest lottery markets in the US',
      'Funds go to public education',
    ],
  },
  texas: {
    name: 'Texas',
    abbreviation: 'TX',
    slug: 'texas',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0,
    taxNotes: 'Texas has no state income tax, so no state tax on lottery winnings.',
    lotteryWebsite: 'https://www.txlottery.org',
    claimInfo: 'Prizes up to $599 at any retailer. $600-$2,499,999 at Texas Lottery claim centers. Over $2.5M at Austin headquarters.',
    purchaseAge: 18,
    facts: [
      'Texas Lottery launched in 1992',
      'No state income tax on winnings',
      'Proceeds support public education and veterans',
      'One of the highest jackpot-producing states',
    ],
  },
  florida: {
    name: 'Florida',
    abbreviation: 'FL',
    slug: 'florida',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0,
    taxNotes: 'Florida has no state income tax. Only federal taxes apply to lottery winnings.',
    lotteryWebsite: 'https://www.flalottery.com',
    claimInfo: 'Prizes up to $599 at retailers. $600-$249,999 at FL Lottery district offices. Over $250,000 at Tallahassee headquarters.',
    purchaseAge: 18,
    facts: [
      'Florida Lottery began in 1988',
      'No state income tax on winnings',
      'Proceeds support education (Bright Futures scholarships)',
      'Home to multiple major jackpot winners',
    ],
  },
  'new-york': {
    name: 'New York',
    abbreviation: 'NY',
    slug: 'new-york',
    availableGames: ['powerball', 'mega-millions', 'cash4life', 'ny-lotto', 'take5'],
    taxRate: 0.109,
    taxNotes: 'New York has the highest combined lottery tax rate. NYC residents pay an additional 3.876%, and Yonkers residents 1.959%.',
    lotteryWebsite: 'https://nylottery.ny.gov',
    claimInfo: 'Prizes up to $600 at retailers. Over $600 at NY Lottery Customer Service Centers or by mail. Over $5,000 requires a visit to a Customer Service Center.',
    purchaseAge: 18,
    facts: [
      'NY Lottery is one of the oldest in the US (1967)',
      'Highest state lottery tax rate at 10.9%',
      'NYC adds additional 3.876% local tax',
      'All proceeds go to education — over $3.5B annually',
    ],
  },
  pennsylvania: {
    name: 'Pennsylvania',
    abbreviation: 'PA',
    slug: 'pennsylvania',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0.0307,
    taxNotes: 'Pennsylvania has a flat 3.07% state tax on lottery winnings — one of the lowest rates.',
    lotteryWebsite: 'https://www.palottery.state.pa.us',
    claimInfo: 'Prizes up to $2,500 at retailers. Over $2,500 at PA Lottery Area Offices. Over $250,000 at Middletown headquarters.',
    purchaseAge: 18,
    facts: [
      'Pennsylvania Lottery started in 1972',
      'Low 3.07% flat state tax rate',
      'Proceeds fund programs for older Pennsylvanians',
      'One of the most popular lottery states',
    ],
  },
  ohio: {
    name: 'Ohio',
    abbreviation: 'OH',
    slug: 'ohio',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.04,
    taxNotes: 'Ohio taxes lottery winnings at 4.0%.',
    lotteryWebsite: 'https://www.ohiolottery.com',
    claimInfo: 'Prizes up to $599 at retailers. Over $600 at OH Lottery regional offices or Cleveland headquarters.',
    purchaseAge: 18,
    facts: [
      'Ohio Lottery began in 1974',
      '4.0% state tax on winnings',
      'Profits fund education in Ohio',
      'Offers a wide variety of games',
    ],
  },
  illinois: {
    name: 'Illinois',
    abbreviation: 'IL',
    slug: 'illinois',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0495,
    taxNotes: 'Illinois has a flat 4.95% state tax on lottery winnings.',
    lotteryWebsite: 'https://www.illinoislottery.com',
    claimInfo: 'Prizes up to $600 at retailers. Over $600 at IL Lottery claim centers in Chicago, Springfield, Fairview Heights, or Rockford.',
    purchaseAge: 18,
    facts: [
      'Illinois Lottery started in 1974',
      'Flat 4.95% state tax rate',
      'First state to sell lottery tickets online',
      'Proceeds support Illinois education',
    ],
  },
  michigan: {
    name: 'Michigan',
    abbreviation: 'MI',
    slug: 'michigan',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0.0425,
    taxNotes: 'Michigan taxes lottery winnings at 4.25%.',
    lotteryWebsite: 'https://www.michiganlottery.com',
    claimInfo: 'Prizes up to $600 at retailers. Over $600 at MI Lottery headquarters in Lansing or by mail.',
    purchaseAge: 18,
    facts: [
      'Michigan Lottery launched in 1972',
      '4.25% state tax on winnings',
      'Proceeds fund Michigan public schools',
      'Over $1 billion annually for education',
    ],
  },
  georgia: {
    name: 'Georgia',
    abbreviation: 'GA',
    slug: 'georgia',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0.0549,
    taxNotes: 'Georgia taxes lottery winnings at 5.49%.',
    lotteryWebsite: 'https://www.galottery.com',
    claimInfo: 'Prizes up to $600 at retailers. Over $600 at GA Lottery claim centers in Atlanta, Savannah, or Macon.',
    purchaseAge: 18,
    facts: [
      'Georgia Lottery began in 1993',
      '5.49% state tax on winnings',
      'Funds the HOPE Scholarship program',
      'Also funds Pre-K education',
    ],
  },
  'north-carolina': {
    name: 'North Carolina',
    abbreviation: 'NC',
    slug: 'north-carolina',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.045,
    taxNotes: 'North Carolina taxes lottery winnings at 4.5%.',
    lotteryWebsite: 'https://www.nclottery.com',
    claimInfo: 'Prizes up to $599 at retailers. $600-$99,999 at NC Education Lottery regional offices. Over $100,000 at Raleigh headquarters.',
    purchaseAge: 18,
    facts: [
      'NC Education Lottery started in 2006',
      '4.5% state tax on winnings',
      'One of the newer state lotteries',
      'Proceeds fund education, school construction, and college scholarships',
    ],
  },
  'arizona': {
    name: 'Arizona',
    abbreviation: 'AZ',
    slug: 'arizona',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.025,
    taxNotes: 'Arizona taxes lottery winnings at 2.5%, one of the lowest rates in the country.',
    lotteryWebsite: 'https://www.azlottery.gov',
    claimInfo: 'Prizes up to $599 can be claimed at any retailer. Prizes from $600 to $99,999 at Arizona Lottery District Offices. Jackpot prizes and amounts over $100,000 must be claimed at Arizona Lottery headquarters in Phoenix.',
    purchaseAge: 21,
    facts: [
      'Arizona Lottery was established in 1981',
      'Lowest tax rate on lottery winnings in the nation at 2.5%',
      'Proceeds support education and health programs',
      'Arizona is home to one of the longest-running lotteries in the US',
    ],
  },
  'arkansas': {
    name: 'Arkansas',
    abbreviation: 'AR',
    slug: 'arkansas',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.044,
    taxNotes: 'Arkansas taxes lottery winnings at 4.4% state tax rate.',
    lotteryWebsite: 'https://www.arkansaslottery.com',
    claimInfo: 'Prizes under $600 can be claimed at any retailer. Prizes from $600 to $99,999 at Arkansas Lottery District Offices. Major jackpot prizes must be claimed at Arkansas Lottery headquarters in Little Rock.',
    purchaseAge: 18,
    facts: [
      'Arkansas Lottery launched in 2009',
      'Supports natural resources and conservation funding',
      'One of the newer state lottery systems',
      'Proceeds benefit education and infrastructure',
    ],
  },
  'colorado': {
    name: 'Colorado',
    abbreviation: 'CO',
    slug: 'colorado',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.044,
    taxNotes: 'Colorado taxes lottery winnings at 4.4% state tax rate.',
    lotteryWebsite: 'https://www.coloradolottery.com',
    claimInfo: 'Prizes under $600 at any retailer. Prizes $600-$99,999 at Colorado Lottery District Offices. Jackpot prizes and major amounts must be claimed at Colorado Lottery headquarters in Denver.',
    purchaseAge: 18,
    facts: [
      'Colorado Lottery began in 1983',
      'Supports parks, recreation, and wildlife programs',
      'One of the earliest state lottery systems',
      'Proceeds benefit conservation and outdoor initiatives',
    ],
  },
  'connecticut': {
    name: 'Connecticut',
    abbreviation: 'CT',
    slug: 'connecticut',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0.0699,
    taxNotes: 'Connecticut taxes lottery winnings at 6.99% state tax rate.',
    lotteryWebsite: 'https://www.ct.gov/lottery',
    claimInfo: 'Prizes under $600 can be claimed at any retailer. Prizes from $600 to $99,999 at Connecticut Lottery District Offices. Jackpot prizes and major amounts must be claimed at Connecticut Lottery headquarters in Newington.',
    purchaseAge: 18,
    facts: [
      'Connecticut Lottery was established in 1972',
      'Supports educational programs and institutions',
      'One of the oldest state lottery systems',
      'Proceeds benefit public education funding',
    ],
  },
  'delaware': {
    name: 'Delaware',
    abbreviation: 'DE',
    slug: 'delaware',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0.066,
    taxNotes: 'Delaware taxes lottery winnings at 6.6%, among the highest state rates in the nation.',
    lotteryWebsite: 'https://www.delaware.gov/lottery',
    claimInfo: 'Prizes under $600 can be claimed at any authorized retailer. Prizes from $600 to $50,000 at Delaware Lottery offices. Jackpot prizes over $50,000 must be claimed at the Delaware Lottery headquarters in Wilmington.',
    purchaseAge: 18,
    facts: [
      'Delaware Lottery was established in 1975',
      'One of the oldest state lotteries in the US',
      'Revenues support education and general fund',
      'Participates in multi-state games and Cash4Life',
    ],
  },
  'idaho': {
    name: 'Idaho',
    abbreviation: 'ID',
    slug: 'idaho',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.058,
    taxNotes: 'Idaho taxes lottery winnings at 5.8% as part of regular state income tax.',
    lotteryWebsite: 'https://www.idaholottery.com',
    claimInfo: 'Prizes under $600 can be claimed at authorized retailers. Prizes from $600 to $10,000 at Idaho Lottery regional offices. Jackpot prizes exceeding $10,000 must be claimed at the Idaho Lottery headquarters in Boise.',
    purchaseAge: 18,
    facts: [
      'Idaho Lottery began operations in 1989',
      'Generates significant revenue for education funding',
      'Supports various state programs and initiatives',
      'Popular multi-state game participant',
    ],
  },
  'indiana': {
    name: 'Indiana',
    abbreviation: 'IN',
    slug: 'indiana',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0305,
    taxNotes: 'Indiana taxes lottery winnings at 3.05%, one of the lowest state tax rates in the nation.',
    lotteryWebsite: 'https://www.indianalottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any lottery retailer. Prizes from $600 to $100,000 are claimed at Indiana Lottery regional offices. Prizes exceeding $100,000 must be claimed at the Indiana Lottery headquarters in Indianapolis.',
    purchaseAge: 21,
    facts: [
      'Indiana Lottery was established in 1989',
      'Lottery revenue supports education and infrastructure',
      'Indiana has one of the lowest state tax rates on winnings',
      'Powerball and Mega Millions are the primary games offered',
    ],
  },
  'iowa': {
    name: 'Iowa',
    abbreviation: 'IA',
    slug: 'iowa',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.057,
    taxNotes: 'Iowa taxes lottery winnings at 5.7%, with proceeds supporting education and infrastructure.',
    lotteryWebsite: 'https://www.ialottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any lottery retailer. Prizes from $600 to $50,000 are claimed at Iowa Lottery regional offices. Major prizes over $50,000 must be claimed at the Iowa Lottery headquarters in Des Moines.',
    purchaseAge: 21,
    facts: [
      'Iowa Lottery began operations in 1985',
      'Lottery funds support education and environment initiatives',
      'Iowa is a member of the Multi-State Lottery Association',
      'Minimum purchase age is 21 in Iowa',
    ],
  },
  'kansas': {
    name: 'Kansas',
    abbreviation: 'KS',
    slug: 'kansas',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.057,
    taxNotes: 'Kansas taxes lottery winnings at 5.7%, with revenue dedicated to public education.',
    lotteryWebsite: 'https://www.kslottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any authorized lottery retailer. Prizes between $600 and $50,000 are claimed at Kansas Lottery regional offices. Prizes exceeding $50,000 must be claimed at the Kansas Lottery headquarters in Topeka.',
    purchaseAge: 18,
    facts: [
      'Kansas Lottery was established in 1987',
      'Lottery revenue supports the Kansas Education Fund',
      'Kansas participates in major multi-state lottery games',
      'The state has a strong retail lottery network',
    ],
  },
  'kentucky': {
    name: 'Kentucky',
    abbreviation: 'KY',
    slug: 'kentucky',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.044,
    taxNotes: 'Kentucky taxes lottery winnings at 4.4%, with proceeds supporting education and horse racing programs.',
    lotteryWebsite: 'https://www.kylottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any participating lottery retailer. Prizes from $600 to $100,000 are claimed at Kentucky Lottery regional offices. Major prizes over $100,000 must be claimed at the Kentucky Lottery headquarters in Louisville.',
    purchaseAge: 18,
    facts: [
      'Kentucky Lottery was established in 1989',
      'Lottery revenue funds education programs and horse racing',
      'Kentucky has a moderate tax rate on lottery winnings',
      'The state is known for strong lottery game participation',
    ],
  },
  'louisiana': {
    name: 'Louisiana',
    abbreviation: 'LA',
    slug: 'louisiana',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0425,
    taxNotes: 'Louisiana taxes lottery winnings at 4.25%, with revenues supporting state education programs.',
    lotteryWebsite: 'https://www.louisianalottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any authorized lottery retailer. Prizes between $600 and $50,000 are claimed at Louisiana Lottery regional offices. Prizes exceeding $50,000 must be claimed at the Louisiana Lottery headquarters in Baton Rouge.',
    purchaseAge: 21,
    facts: [
      'Louisiana Lottery was established in 1991',
      'Lottery revenue supports education and infrastructure',
      'Louisiana has a competitive tax rate on winnings',
      'The state has extensive lottery retail availability',
    ],
  },
  'maine': {
    name: 'Maine',
    abbreviation: 'ME',
    slug: 'maine',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0.0715,
    taxNotes: 'Maine taxes lottery winnings at 7.15% state income tax rate.',
    lotteryWebsite: 'https://www.maine.gov/ifw/lottery',
    claimInfo: 'Prizes up to $599 can be claimed at any retailer. Prizes from $600 to $99,999 at Maine Lottery regional offices. Jackpot prizes over $100,000 must be claimed at Maine Lottery headquarters in Augusta.',
    purchaseAge: 18,
    facts: [
      'Maine Lottery was established in 1974',
      'Maine is part of the tri-state lottery consortium',
      'Lottery revenue supports education and outdoor recreation programs',
      'Maine offers Cash4Life as a regional game option',
    ],
  },
  'maryland': {
    name: 'Maryland',
    abbreviation: 'MD',
    slug: 'maryland',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0.0875,
    taxNotes: 'Maryland taxes lottery winnings at 8.75% state income tax rate.',
    lotteryWebsite: 'https://www.marylandlottery.com',
    claimInfo: 'Prizes up to $500 can be claimed at any retailer. Prizes from $500 to $100,000 at Maryland Lottery claim centers. Jackpot prizes over $100,000 must be claimed at lottery headquarters in Baltimore.',
    purchaseAge: 18,
    facts: [
      'Maryland Lottery was established in 1973',
      'Lottery funds support education, public safety, and environmental programs',
      'Maryland participates in Cash4Life regional lottery',
      'One of the oldest state lotteries in the US',
    ],
  },
  'massachusetts': {
    name: 'Massachusetts',
    abbreviation: 'MA',
    slug: 'massachusetts',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0.05,
    taxNotes: 'Massachusetts taxes lottery winnings at 5% state income tax rate, one of the lowest in the nation.',
    lotteryWebsite: 'https://www.masslottery.com',
    claimInfo: 'Prizes up to $600 can be claimed at any retailer. Prizes from $600 to $100,000 at Massachusetts Lottery regional offices. Jackpot prizes over $100,000 must be claimed at lottery headquarters in Boston.',
    purchaseAge: 18,
    facts: [
      'Massachusetts Lottery was established in 1971',
      'Massachusetts has one of the lowest lottery tax rates in the US',
      'Lottery revenue funds public education and local aid to cities and towns',
      'Massachusetts offers Cash4Life in addition to national games',
    ],
  },
  'minnesota': {
    name: 'Minnesota',
    abbreviation: 'MN',
    slug: 'minnesota',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0985,
    taxNotes: 'Minnesota taxes lottery winnings at 9.85% state income tax rate, among the highest in the nation.',
    lotteryWebsite: 'https://www.mnlottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any retailer. Prizes from $600 to $50,000 at Minnesota Lottery regional offices. Jackpot prizes over $50,000 must be claimed at lottery headquarters in St. Paul.',
    purchaseAge: 18,
    facts: [
      'Minnesota Lottery was established in 1989',
      'Minnesota has one of the highest lottery tax rates in the nation',
      'Lottery revenue supports environmental and natural resource programs',
      'Minnesota is a significant participant in national lottery games',
    ],
  },
  'mississippi': {
    name: 'Mississippi',
    abbreviation: 'MS',
    slug: 'mississippi',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.05,
    taxNotes: 'Mississippi taxes lottery winnings at 5% state income tax rate.',
    lotteryWebsite: 'https://www.mslottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any retailer. Prizes $600-$100,000 at Mississippi Lottery regional offices. Jackpot prizes over $100,000 claimed at headquarters in Jackson.',
    purchaseAge: 18,
    facts: [
      'Mississippi Lottery was established in 2019',
      'Proceeds support education and infrastructure',
      'One of the newest state lottery systems in the US',
      'Offers both Powerball and Mega Millions games',
    ],
  },
  'missouri': {
    name: 'Missouri',
    abbreviation: 'MO',
    slug: 'missouri',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.048,
    taxNotes: 'Missouri taxes lottery winnings at approximately 4.8% state income tax rate.',
    lotteryWebsite: 'https://www.molottery.com',
    claimInfo: 'Prizes under $600 claimed at any retailer. Prizes $600-$5,000 at Missouri Lottery regional offices. Prizes over $5,000 at lottery headquarters in Jefferson City.',
    purchaseAge: 18,
    facts: [
      'Missouri Lottery launched in 1986',
      'Supports education and conservation programs',
      'One of the mid-sized lottery markets',
      'Has produced numerous multimillion-dollar jackpot winners',
    ],
  },
  'montana': {
    name: 'Montana',
    abbreviation: 'MT',
    slug: 'montana',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.059,
    taxNotes: 'Montana taxes lottery winnings at approximately 5.9% state income tax rate.',
    lotteryWebsite: 'https://www.montanalottery.com',
    claimInfo: 'Small prizes up to $599 redeemable at any retailer. Prizes $600-$10,000 at Montana Lottery regional offices. Major jackpot prizes claimed at Helena headquarters.',
    purchaseAge: 18,
    facts: [
      'Montana Lottery established in 1987',
      'Funds support education and infrastructure',
      'Rural lottery participation is significant',
      'Part of Western Lottery Association multistate games',
    ],
  },
  'nebraska': {
    name: 'Nebraska',
    abbreviation: 'NE',
    slug: 'nebraska',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0584,
    taxNotes: 'Nebraska taxes lottery winnings at approximately 5.84% state income tax rate.',
    lotteryWebsite: 'https://www.nelottery.com',
    claimInfo: 'Prizes under $600 can be claimed at any retailer. Prizes $600-$5,000 at Nebraska Lottery regional offices. Jackpot prizes over $5,000 claimed at Lincoln headquarters.',
    purchaseAge: 21,
    facts: [
      'Nebraska Lottery began in 1993',
      'Supports education and environmental programs',
      'Must be 21 to purchase lottery tickets in Nebraska',
      'One of the country\'s most responsible gaming programs',
    ],
  },
  'new-hampshire': {
    name: 'New Hampshire',
    abbreviation: 'NH',
    slug: 'new-hampshire',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0,
    taxNotes: 'New Hampshire does not tax lottery winnings — one of the few states offering tax-free jackpots.',
    lotteryWebsite: 'https://www.nhlottery.com',
    claimInfo: 'Prizes up to $600 claimed at any retailer. Prizes $600-$25,000 at New Hampshire Lottery offices. Jackpot prizes over $25,000 claimed at Concord headquarters.',
    purchaseAge: 18,
    facts: [
      'New Hampshire Lottery established in 1964',
      'No state income tax on lottery winnings',
      'One of the oldest state lottery systems',
      'Proceeds support education funding',
    ],
  },
  'new-jersey': {
    name: 'New Jersey',
    abbreviation: 'NJ',
    slug: 'new-jersey',
    availableGames: ['powerball', 'mega-millions', 'cash4life'],
    taxRate: 0.08,
    taxNotes: 'New Jersey taxes lottery winnings at 8% state tax, plus federal withholding applies to larger prizes.',
    lotteryWebsite: 'https://www.nj.gov/lottery',
    claimInfo: 'Prizes up to $599 can be claimed at any retailer. Prizes $600-$10,000 at New Jersey Lottery regional offices. Prizes over $10,000 must be claimed at New Jersey Lottery headquarters in Trenton.',
    purchaseAge: 18,
    facts: [
      'New Jersey Lottery was established in 1970',
      'Cash4Life game is available exclusively in northeastern states',
      'Lottery proceeds support education and veterans programs',
      'One of the oldest state lotteries in the United States',
    ],
  },
  'new-mexico': {
    name: 'New Mexico',
    abbreviation: 'NM',
    slug: 'new-mexico',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.059,
    taxNotes: 'New Mexico taxes lottery winnings at approximately 5.9% state income tax, in addition to federal taxes.',
    lotteryWebsite: 'https://www.nmlottery.com',
    claimInfo: 'Prizes under $600 can be claimed at any authorized retailer. Prizes $600-$100,000 at New Mexico Lottery regional offices. Prizes exceeding $100,000 must be claimed at lottery headquarters in Santa Fe.',
    purchaseAge: 18,
    facts: [
      'New Mexico Lottery began operations in 1996',
      'Funds support public education throughout the state',
      'Relatively modest state income tax rate compared to national average',
      'Draws are held multiple times weekly for major games',
    ],
  },
  'north-dakota': {
    name: 'North Dakota',
    abbreviation: 'ND',
    slug: 'north-dakota',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0195,
    taxNotes: 'North Dakota has one of the lowest state tax rates in the nation at approximately 1.95% on lottery winnings.',
    lotteryWebsite: 'https://www.nd.gov/gnf/lottery',
    claimInfo: 'Prizes under $600 can be claimed at any authorized retailer. Prizes $600-$10,000 at North Dakota Lottery offices. Prizes over $10,000 must be claimed at lottery headquarters.',
    purchaseAge: 18,
    facts: [
      'North Dakota has one of the lowest lottery tax rates in the United States',
      'Lottery revenue supports education and infrastructure projects',
      'Relatively small lottery market compared to larger states',
      'Draws occur multiple times per week for major games',
    ],
  },
  'oklahoma': {
    name: 'Oklahoma',
    abbreviation: 'OK',
    slug: 'oklahoma',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0475,
    taxNotes: 'Oklahoma taxes lottery winnings at approximately 4.75% state income tax rate.',
    lotteryWebsite: 'https://www.oklahomalgc.com',
    claimInfo: 'Prizes under $600 can be claimed at any authorized retailer. Prizes $600-$10,000 at Oklahoma Lottery regional offices. Prizes over $10,000 must be claimed at Oklahoma Lottery headquarters in Oklahoma City.',
    purchaseAge: 18,
    facts: [
      'Oklahoma Lottery began in 2009',
      'One of the newest state lotteries in the United States',
      'Revenue supports public education and other state programs',
      'Offers multiple daily drawing opportunities',
    ],
  },
  'oregon': {
    name: 'Oregon',
    abbreviation: 'OR',
    slug: 'oregon',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.099,
    taxNotes: 'Oregon taxes lottery winnings at 9.9%, one of the highest state tax rates in the nation.',
    lotteryWebsite: 'https://www.oregonlottery.org',
    claimInfo: 'Prizes up to $599 can be claimed at any authorized retailer. Prizes from $600 to $4,999 at Oregon Lottery district offices. Prizes of $5,000 or more must be claimed at Oregon Lottery headquarters in Salem.',
    purchaseAge: 18,
    facts: [
      'Oregon Lottery was established in 1985',
      'Highest state tax rate on lottery winnings at 9.9%',
      'Proceeds support education, public safety, and community programs',
      'Oregon does not have a state Lotto game',
    ],
  },
  'rhode-island': {
    name: 'Rhode Island',
    abbreviation: 'RI',
    slug: 'rhode-island',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0599,
    taxNotes: 'Rhode Island taxes lottery winnings at 5.99%, a moderate state tax rate on lottery prizes.',
    lotteryWebsite: 'https://www.rilottery.com',
    claimInfo: 'Prizes up to $600 can be claimed at any authorized retailer. Prizes from $600 to $100,000 at Rhode Island Lottery claim centers. Prizes over $100,000 must be claimed at RI Lottery headquarters in Cranston.',
    purchaseAge: 18,
    facts: [
      'Rhode Island Lottery began operations in 1974',
      'State tax on winnings is 5.99%',
      'Proceeds support education, infrastructure, and city/town aid programs',
      'Rhode Island is home to one of the oldest lottery organizations in the US',
    ],
  },
  'south-carolina': {
    name: 'South Carolina',
    abbreviation: 'SC',
    slug: 'south-carolina',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.064,
    taxNotes: 'South Carolina taxes lottery winnings at 6.4%, a moderate state tax rate on lottery prizes.',
    lotteryWebsite: 'https://www.sclottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any lottery retailer. Prizes from $600 to $100,000 at South Carolina Lottery regional claim centers. Prizes exceeding $100,000 must be claimed at SC Lottery headquarters in Columbia.',
    purchaseAge: 18,
    facts: [
      'South Carolina Lottery was established in 2002',
      'State tax on winnings is 6.4%',
      'Proceeds support education and public safety initiatives',
      'South Carolina has produced numerous jackpot winners since its inception',
    ],
  },
  'south-dakota': {
    name: 'South Dakota',
    abbreviation: 'SD',
    slug: 'south-dakota',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0,
    taxNotes: 'South Dakota has no state income tax, so lottery winnings are not subject to state income tax.',
    lotteryWebsite: 'https://lottery.sd.gov',
    claimInfo: 'Prizes up to $500 can be claimed at any lottery retailer. Prizes from $500 to $1,000,000 at South Dakota Lottery claim centers. Prizes over $1,000,000 must be claimed at SD Lottery headquarters in Pierre.',
    purchaseAge: 18,
    facts: [
      'South Dakota Lottery was established in 1987',
      'No state income tax on lottery winnings',
      'Proceeds support K-12 education and water projects',
      'South Dakota is one of the few states with no tax on lottery prizes',
    ],
  },
  'tennessee': {
    name: 'Tennessee',
    abbreviation: 'TN',
    slug: 'tennessee',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0,
    taxNotes: 'Tennessee does not tax lottery winnings, making it one of the most favorable states for lottery winners.',
    lotteryWebsite: 'https://www.tnlottery.com',
    claimInfo: 'Prizes up to $599 can be claimed at any retailer. Prizes from $600 to $5,000 at Tennessee Lottery regional offices. Prizes over $5,000 must be claimed at the Tennessee Lottery headquarters in Nashville.',
    purchaseAge: 18,
    facts: [
      'Tennessee Lottery began operations in 2004',
      'No state tax on lottery winnings',
      'Proceeds benefit education programs across the state',
      'One of the newer state lotteries in the US',
    ],
  },
  'vermont': {
    name: 'Vermont',
    abbreviation: 'VT',
    slug: 'vermont',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0875,
    taxNotes: 'Vermont taxes lottery winnings at 8.75%, one of the state\'s income tax rates applied to prize earnings.',
    lotteryWebsite: 'https://www.vermontlottery.com',
    claimInfo: 'Prizes up to $600 can be claimed at any lottery retailer. Prizes from $600 to $100,000 at Vermont Lottery offices. Prizes over $100,000 must be claimed at the lottery headquarters in Montpelier.',
    purchaseAge: 18,
    facts: [
      'Vermont Lottery operates as a multi-state lottery participant',
      'Winnings are subject to state income tax at 8.75%',
      'Lottery revenue supports education and infrastructure',
      'One of the smallest lottery markets in the US',
    ],
  },
  'virginia': {
    name: 'Virginia',
    abbreviation: 'VA',
    slug: 'virginia',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0575,
    taxNotes: 'Virginia taxes lottery winnings at 5.75%, applied as part of the state\'s income tax system.',
    lotteryWebsite: 'https://www.valottery.com',
    claimInfo: 'Prizes up to $500 can be claimed at any lottery retailer. Prizes from $500 to $25,000 at Virginia Lottery regional offices. Prizes over $25,000 must be claimed at lottery headquarters in Richmond.',
    purchaseAge: 18,
    facts: [
      'Virginia Lottery was established in 1987',
      'Winnings taxed at 5.75% state income tax rate',
      'Generates significant revenue for K-12 education',
      'One of the oldest lotteries on the East Coast',
    ],
  },
  'washington': {
    name: 'Washington',
    abbreviation: 'WA',
    slug: 'washington',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0,
    taxNotes: 'Washington does not impose state income tax on lottery winnings, giving winners a significant advantage.',
    lotteryWebsite: 'https://www.walottery.com',
    claimInfo: 'Prizes up to $250 can be claimed at any retailer. Prizes from $250 to $1,000 at Washington Lottery regional offices. Prizes over $1,000 must be claimed at lottery headquarters in Olympia.',
    purchaseAge: 18,
    facts: [
      'Washington Lottery has been operating since 1982',
      'No state income tax on lottery prize winnings',
      'Supports education, veterans, and public safety programs',
      'One of the most popular lottery states in the Pacific Northwest',
    ],
  },
  'west-virginia': {
    name: 'West Virginia',
    abbreviation: 'WV',
    slug: 'west-virginia',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.065,
    taxNotes: 'West Virginia taxes lottery winnings at 6.5% state income tax rate.',
    lotteryWebsite: 'https://www.wvlottery.com',
    claimInfo: 'Prizes up to $500 can be claimed at any retailer. Prizes $500-$100,000 at West Virginia Lottery regional offices. Over $100,000 at lottery headquarters in Charleston.',
    purchaseAge: 18,
    facts: [
      'West Virginia Lottery was established in 1985',
      'State income tax of 6.5% applies to all lottery winnings',
      'Proceeds support public education and senior services',
      'One of the older lottery systems in the United States',
    ],
  },
  'wisconsin': {
    name: 'Wisconsin',
    abbreviation: 'WI',
    slug: 'wisconsin',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.0765,
    taxNotes: 'Wisconsin taxes lottery winnings at 7.65% combined state income tax rate.',
    lotteryWebsite: 'https://www.wilottery.com',
    claimInfo: 'Prizes up to $500 at any lottery retailer. Prizes $500-$100,000 at Wisconsin Lottery regional claim centers. Over $100,000 at lottery headquarters in Madison.',
    purchaseAge: 18,
    facts: [
      'Wisconsin Lottery began operations in 1988',
      'Combined state tax rate of 7.65% on lottery winnings',
      'Revenue supports K-12 education and property tax relief',
      'Wisconsin is known for high lottery participation rates',
    ],
  },
  'wyoming': {
    name: 'Wyoming',
    abbreviation: 'WY',
    slug: 'wyoming',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0,
    taxNotes: 'Wyoming has no state income tax, so lottery winnings are not taxed by the state.',
    lotteryWebsite: 'https://www.wyomingonline.com',
    claimInfo: 'Prizes up to $500 can be claimed at any retailer. Prizes $500-$5,000 at Wyoming Lottery claim centers. Over $5,000 at lottery headquarters in Cheyenne.',
    purchaseAge: 18,
    facts: [
      'Wyoming Lottery was established in 1988',
      'No state income tax on lottery winnings',
      'Proceeds benefit public education in Wyoming',
      'Wyoming is one of the most tax-friendly lottery states',
    ],
  },
  'district-of-columbia': {
    name: 'District of Columbia',
    abbreviation: 'DC',
    slug: 'district-of-columbia',
    availableGames: ['powerball', 'mega-millions'],
    taxRate: 0.1075,
    taxNotes: 'District of Columbia taxes lottery winnings at 10.75%, one of the highest state tax rates on lottery prizes.',
    lotteryWebsite: 'https://www.dclottery.com',
    claimInfo: 'Prizes up to $500 at any authorized retailer. Prizes $500-$50,000 at DC Lottery claim center locations. Over $50,000 at DC Lottery headquarters.',
    purchaseAge: 18,
    facts: [
      'DC Lottery was established in 1981',
      'Highest state tax rate on lottery winnings at 10.75%',
      'Revenue supports public education and youth programs',
      'DC Lottery is one of the oldest state lotteries',
    ],
  },
};

export function getState(slug: string): StateConfig | undefined {
  return stateConfigs[slug];
}

export function getAllStates(): StateConfig[] {
  return Object.values(stateConfigs);
}

export function getAllStateSlugs(): string[] {
  return Object.keys(stateConfigs);
}
